project:
  type: website
  output-dir: docs

website:
  title: "Workshop on Areal Data"
  navbar:
    left:
      - href: index.qmd
        text: Workshop
      - href: Section1.qmd
        text: Installing bigDM
      - href: Section2.qmd
        text: Spatial models
      - href: Section3.qmd
        text: Multivariate models
      - href: Section4.qmd
        text: Spatio-temporal models
  
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    link-external-newwindow: true

editor: visual
